Repository NBCAndroid15/TripSync, pull requests merged in 2023-11, with the labels that each got.

#88 [Plan-page] plansearch에서 현 위치와 아이템 간의 거리 계산하는 기능을 구현했습니다.
  app/src/main/java/com/example/tripsync/data/CommunityRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/model/ContentPost.kt
  app/src/main/java/com/example/tripsync/model/Post.kt
  app/src/main/java/com/example/tripsync/model/UserPost.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/CommunityWriteFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/LocationUtility.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanUserNameAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/planbookmarklist/PlanBoomarkListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/plan_search_list_item.xml
  app/src/main/res/layout/plan_username_item.xml
Labels: feature

#90 [search-page] 레이아웃 UI 수정과 검색 결과, 결과 페이지 기능을 수정 했습니다.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tripsync/ui/fragment/CommunityContentFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchFragment.kt
  app/src/main/res/layout/fragment_community_content.xml
  app/src/main/res/layout/fragment_community_write.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_search.xml
Labels: refactor

#91 [plan-page]
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/LocationUtility.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanMemoListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanNaverMap.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanSwapManage.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/planbookmarklist/PlanBookmarkListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/planbookmarklist/PlanBoomarkListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_search2.xml
  app/src/main/res/layout/fragment_naver_map.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_plan_boomark_list.xml
  app/src/main/res/layout/fragment_plan_search_list.xml
  app/src/main/res/layout/plan_bookmark_list_item.xml
  app/src/main/res/layout/plan_search_list_item.xml
Labels: feature, design

#95 [Login] : 구글 로그인 기능 안정화
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#96 [search-page] 검색어 키워드 자동완성 기능을 구현하였습니다.
  app/build.gradle
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchFragment.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_search.xml
Labels: feature

#97 [FEAT] : 비회원 기능
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/FeedListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/FeedListFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/res/layout/feed_list_item.xml
  app/src/main/res/layout/fragment_feed_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_main.xml
Labels: feature, design

#98 [Plan-page] PlanBookmark / PlanSearch 아이템 추가 버튼 이미지 변경
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/model/Travel.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/planbookmarklist/PlanBookmarkListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/planbookmarklist/PlanBoomarkListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/res/drawable/ic_plansearch_add.png
  app/src/main/res/drawable/ic_plansearch_plus.png
  app/src/main/res/layout/fragment_plan_search_list.xml
  app/src/main/res/layout/fragment_setup.xml
  app/src/main/res/layout/plan_bookmark_list_item.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/plan_search_list_item.xml
  gradlew
Labels: feature, design

#99 [Design] : 마이 페이지, 서치 페이지 디자인 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchFragment.kt
  app/src/main/res/layout/fragment_bookmark_manage.xml
  app/src/main/res/layout/fragment_friend_manage.xml
  app/src/main/res/layout/fragment_search.xml
Labels: design

#100 Feat/search
  app/src/main/java/com/example/tripsync/data/TravelApiService.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFestivalAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/res/drawable/coin_banner_img.png
  app/src/main/res/layout/area_item.xml
  app/src/main/res/layout/festival_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/travel_item.xml
Labels: feature, refactor, design

#102 동전 게임 배너 클릭시 프래그먼트 -> 뷰페이저 전환으로 변경
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
Labels: refactor

#103 [Main-Fragment] : 백버튼 종료
  .idea/deploymentTargetDropDown.xml
  Screenshot_20231107_095232.png
  Screenshot_20231107_095409.png
  Screenshot_20231107_095651.png
  Screenshot_20231107_100128.png
  Screenshot_20231107_100342.png
  Screenshot_20231107_100416.png
  Screenshot_20231107_100517.png
  Screenshot_20231107_100722.png
  Screenshot_20231107_100733.png
  app/src/main/java/com/example/tripsync/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
Labels: feature

#104 [MyPlan] : 힌트 메시지 추가
  app/src/main/java/com/example/tripsync/ui/fragment/MyPlanFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_plan.xml
  app/src/main/res/layout/fragment_user_manage.xml
Labels: feature

#107 Feature/detail
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/trip/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/MapFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_search.xml
Labels: feature

#108 [PlanFragment] PlanFragment에서 모든 아이템 클릭 시 디테일로 이동 및 다른 날짜 페이지 이동
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/trip/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/PlanListAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/planbookmarklist/PlanBookmarkListAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/planbookmarklist/PlanBoomarkListDialog.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/res/drawable/next.png
  app/src/main/res/drawable/previous.png
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_plan_boomark_list.xml
Labels: feature, design

#109 [UI] : UI 수정 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/trip/tripsync/MyApplication.kt
  app/src/main/java/com/trip/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/trip/tripsync/ui/adapter/FriendAddAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/adapter/FriendManageAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/dialog/FriendAddDialogFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/setup/setupuseradd/SetupUserAddDialogAdapter.kt
  app/src/main/res/layout/bookmarkmanage_bookmark_item.xml
  app/src/main/res/layout/friendmanage_friend_add_item.xml
  app/src/main/res/layout/friendmanage_friend_item.xml
  app/src/main/res/layout/plan_user_add_item.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: design

#111 [signup-page] : 회원가입 시 닉네임 자릿수 제한 기능을 구현하였습니다.
  app/src/main/java/com/trip/tripsync/ui/fragment/SignupFragment.kt
  app/src/main/res/drawable/ic_setup_right.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_signup.xml
Labels: feature, refactor

#112 [Feat] : 자동로그인 기능
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/trip/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/SignOutDialogFragment.kt
Labels: feature

#113 [Plan-페이지] 플랜 북마크, 검색 거리순으로 나열되게 했습니다.
  .idea/deploymentTargetDropDown.xml
  Screenshot_20231107_095232.png
  Screenshot_20231107_095409.png
  Screenshot_20231107_095651.png
  Screenshot_20231107_100128.png
  Screenshot_20231107_100342.png
  Screenshot_20231107_100416.png
  Screenshot_20231107_100517.png
  Screenshot_20231107_100722.png
  Screenshot_20231107_100733.png
  app/src/main/java/com/trip/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/LocationUtility.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/PlanListAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/PlanUserDialogAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/PlanUserNameAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/planbookmarklist/PlanBookmarkListAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/planbookmarklist/PlanBoomarkListDialog.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/SearchViewModel.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/trip/tripsync/viewmodel/BookmarkManageViewModel.kt
  app/src/main/res/layout/fragment_plan_boomark_list.xml
  app/src/main/res/layout/fragment_plan_search_list.xml
  app/src/main/res/layout/plan_bookmark_list_item.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/plan_search_list_item.xml
Labels: feature

#115 [FEAT] : opt
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeFestivalAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeTravelAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/SearchViewModel.kt
Labels: feature

#116 [FEAT] : 북마크 업데이트
  app/src/main/java/com/trip/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/res/drawable/ic_bookmark_blue.png
  app/src/main/res/drawable/ic_bookmark_white.png
  app/src/main/res/layout/fragment_detail.xml
Labels: feature

#118 [FEAT] : transition
  app/build.gradle
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeFestivalAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeTravelAdapter.kt
  app/src/main/res/layout/festival_item.xml
Labels: feature

#119 [fix] : 디테일 북마크 기능 수정
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/trip/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: feature

#120 [FEAT] : bookmark
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/trip/tripsync/ui/fragment/BookmarkManageFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeFestivalAdapter.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/planbookmarklist/PlanBoomarkListDialog.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/search/SearchFragment.kt
Labels: feature

#122 [guide-page] : 홈, 셋업, 플랜 페이지의 가이드 기능을 구현 했습니다.
  app/src/main/java/com/trip/tripsync/ui/fragment/CoinFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/HomeGuideFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/PlanGuideFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/SetupGuideFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/trip/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/res/drawable/border_white_line.xml
  app/src/main/res/drawable/guide_img01.png
  app/src/main/res/drawable/guide_img02.png
  app/src/main/res/drawable/guide_img03.png
  app/src/main/res/layout/fragment_home_guide.xml
  app/src/main/res/layout/fragment_plan_guide.xml
  app/src/main/res/layout/fragment_setup_guide.xml
Labels: feature, refactor, design

#123 [FEAT] : user
  app/src/main/java/com/trip/tripsync/data/AuthRepositoryImpl.kt
Labels: feature

#124 가이드 이미지 가운데 정렬로 변경
  app/src/main/res/layout/fragment_home_guide.xml
  app/src/main/res/layout/fragment_plan_guide.xml
Labels: design
