Repository NBCAndroid15/TripSync, pull requests merged in 2023-10, with the labels that each got.

#6 [FEAT] : Tour API 연동
  .idea/vcs.xml
  app/src/main/java/com/example/tripsync/data/BookmarkRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/data/TravelApiService.kt
  app/src/main/java/com/example/tripsync/data/TravelRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/model/Bookmark.kt
  app/src/main/java/com/example/tripsync/model/Travel.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/util/MyUtil.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: enhancement

#8 Design/user
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  app/src/main/res/drawable/border_user_edit.xml
  app/src/main/res/drawable/button_login_google.xml
  app/src/main/res/drawable/button_main_solid.xml
  app/src/main/res/drawable/button_main_stroke.xml
  app/src/main/res/drawable/button_signup_remove.xml
  app/src/main/res/drawable/button_sub_solid.xml
  app/src/main/res/drawable/ic_google.png
  app/src/main/res/drawable/ic_remove.png
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Design

#10 [DESIGN] : detail fragment ui 작업
  .idea/misc.xml
  app/src/main/res/drawable/ic_back.png
  app/src/main/res/drawable/ic_plus.png
  app/src/main/res/drawable/ic_search.png
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
Labels: design

#11 [DESIGN] : search fragment ui 작업
  app/src/main/res/drawable/logo_main.png
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/xml/fragment_search_xml_constraintlayout_scene.xml
Labels: design

#12 PlanLayout 작업 했습니다.
  .idea/render.experimental.xml
  app/.idea/.gitignore
  app/.idea/gradle.xml
  app/.idea/misc.xml
  app/.idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupCalendarView.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupTitleDialog.kt
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/drawable/ic_plan_user.xml
  app/src/main/res/drawable/ic_setup_right.xml
  app/src/main/res/drawable/plan_btn_background.xml
  app/src/main/res/drawable/plan_map_test.png
  app/src/main/res/drawable/setup_btn_round.xml
  app/src/main/res/drawable/setup_calendar_element.xml
  app/src/main/res/drawable/setup_calendar_selector.xml
  app/src/main/res/drawable/setup_dialog.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_setup.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/setup_calendarview.xml
  app/src/main/res/layout/setup_recycler_date_item.xml
  app/src/main/res/layout/setup_title_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle.properties
  settings.gradle
Labels: design

#17 [DESIGN] : mypage UI
  app/src/main/java/com/example/tripsync/data/AuthRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/model/UserBookmark.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPageViewModelFactory.kt
  app/src/main/res/drawable/baseline_play_arrow_24.xml
  app/src/main/res/layout/bookmarkmanage_bookmark_item.xml
  app/src/main/res/layout/bookmarkmanage_category_item.xml
  app/src/main/res/layout/fragment_bookmark_manage.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_plan.xml
  app/src/main/res/layout/myplan_detail_item.xml
  app/src/main/res/layout/myplan_plan_item.xml
Labels: design

#20 [FEAT] : 북마크, 내 여행지 출력 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/adapter/BookmarkManageAdapter.kt
  app/src/main/java/com/example/tripsync/ui/adapter/MyPlanAdapter.kt
  app/src/main/java/com/example/tripsync/ui/adapter/MyPlanDetailAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/BookmarkManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPlanFragment.kt
  app/src/main/java/com/example/tripsync/viewmodel/BookmarkManageViewModel.kt
  app/src/main/java/com/example/tripsync/viewmodel/BookmarkManageViewModelFactory.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPlanViewModel.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPlanViewModelFactory.kt
  app/src/main/res/drawable/ic_bookmark_delete.png
  app/src/main/res/layout/bookmarkmanage_bookmark_item.xml
  app/src/main/res/layout/fragment_bookmark_manage.xml
  app/src/main/res/layout/fragment_my_plan.xml
  app/src/main/res/layout/myplan_detail_item.xml
  app/src/main/res/layout/myplan_plan_item.xml
Labels: enhancement

#23 Feature/login
  app/build.gradle
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/SignupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanViewType.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: feature, design

#24 [FEAT] : MyPlanFragment 기능 구현
  app/src/main/java/com/example/tripsync/data/AuthRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/model/Travel.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/adapter/ViewPagerFragmentAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_main.xml
Labels: enhancement

#25 Feature/login
  app/build.gradle
  app/google-services.json
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  build.gradle
Labels: feature

#27 [FEAT] : 다이얼로그 추가
  .idea/misc.xml
  app/google-services.json
  app/src/main/java/com/example/tripsync/ui/dialog/ConfirmDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/BookmarkManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/res/drawable/view_round_white_6.xml
  app/src/main/res/layout/fragment_confirm_dialog.xml
Labels: enhancement

#29 [FEAT] : PlanFragment
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/tripsync/model/Plan.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanMemoFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanViewType.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/TestModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupCalendarView.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/res/drawable/ic_plan_editbtn.png
  app/src/main/res/layout/fragment_naver_map.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_plan_memo.xml
  app/src/main/res/layout/plan_edit_view.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/setup_recycler_date_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#31 [FEAT] : 검색 기능 추가
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/adapter/ViewPagerFragmentAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/SearchFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchFragment.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_item.xml
  app/src/main/res/xml/fragment_search_xml_constraintlayout_scene.xml
Labels: feature

#33 [FEAT] : Plan Item List
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tripsync/model/Travel.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanMemoFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/TestModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/planbookmarklist/PlanBookmarkListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/planbookmarklist/PlanBoomarkListFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/SearchViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/SearchViewModelFactory.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/java/com/example/tripsync/viewmodel/BookmarkManageViewModel.kt
  app/src/main/res/drawable/ic_planbooklist_check.xml
  app/src/main/res/drawable/ic_planbooklist_checkbox.xml
  app/src/main/res/drawable/ic_planbooklist_close.xml
  app/src/main/res/layout/fragment_plan_boomark_list.xml
  app/src/main/res/layout/fragment_plan_search_list.xml
  app/src/main/res/layout/plan_bookmark_list_item.xml
  app/src/main/res/layout/plan_search_list_item.xml
Labels: feature, design

#34 [FEAT] : Google 로그인 User 데이터 저장 구현
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/SignupFragment.kt
Labels: feature

#36 Feature/home
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tripsync/data/TravelApiService.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeTravelAdapter.kt
  app/src/main/res/drawable/item_error.jpg
  app/src/main/res/layout/travel_item.xml
Labels: feature, design

#39 [FEAT] : 서치 아이템 클릭
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchFragment.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/search_item.xml
Labels: feature

#40 [FEAT] : 디테일 페이지 버튼 클릭
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchFragment.kt
  app/src/main/res/layout/fragment_bookmark_manage.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_setup.xml
Labels: feature

#41 Feature/home
  app/src/main/java/com/example/tripsync/ui/adapter/ViewPagerFragmentAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/CoinFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MainFragment.kt
  app/src/main/res/anim/coin_effect.xml
  app/src/main/res/drawable/coin_back.png
  app/src/main/res/drawable/coin_front.png
  app/src/main/res/drawable/coin_img01.png
  app/src/main/res/drawable/coin_img02.png
  app/src/main/res/drawable/coin_img03.png
  app/src/main/res/drawable/home_sample.jpg
  app/src/main/res/drawable/home_text.jpg
  app/src/main/res/layout/fragment_coin.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/raw/coin_effect.mp3
Labels: feature, design

#42 [FEAT] : navermap 좌표, 유저목록
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanMemoDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanUserNameAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/SwipeToDeleteCallback.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/TestModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/planbookmarklist/PlanBoomarkListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/SearchViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/setupuseradd/SetupUserAddDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/setupuseradd/SetupUserAddDialogAdapter.kt
  app/src/main/res/drawable/ic_plan_item_number.png
  app/src/main/res/drawable/ic_setup_add.xml
  app/src/main/res/drawable/ic_setup_calendar.xml
  app/src/main/res/drawable/ic_setup_title.xml
  app/src/main/res/drawable/ic_user_person.xml
  app/src/main/res/drawable/plan_item_number.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_plan_boomark_list.xml
  app/src/main/res/layout/fragment_plan_search_list.xml
  app/src/main/res/layout/fragment_plan_user_add_dialog.xml
  app/src/main/res/layout/fragment_setup.xml
  app/src/main/res/layout/plan_bookmark_list_item.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/plan_search_list_item.xml
  app/src/main/res/layout/plan_user_add_item.xml
  app/src/main/res/layout/plan_username_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#45 [FEAT] : 디테일 프래그먼트 기능 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/SignupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchAdapter.kt
  app/src/main/java/com/example/tripsync/viewmodel/MapViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_map.xml
Labels: feature

#46 Feature/splash
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/tripsync/ui/activity/SplashActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/CoinFragment.kt
  app/src/main/res/anim/splash_effect.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/splash_logo.jpg
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: feature

#47 [DESIGN] : 프로그래스 바 레이아웃 제작
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/fragment_coin.xml
Labels: design

#48 [FEAT] : Plan Model
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tripsync/model/Plan.kt
  app/src/main/java/com/example/tripsync/model/PlanDetail.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanMemoListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/SearchViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_setup.xml
  app/src/main/res/layout/plan_memo_item.xml
  app/src/main/res/layout/plan_username_item.xml
Labels: feature

#50 [FEAT] : MyPlanFragment 기능 구현
  app/src/main/java/com/example/tripsync/data/AuthRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/data/PlanRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/ui/adapter/BookmarkManageAdapter.kt
  app/src/main/java/com/example/tripsync/ui/adapter/MyPlanAdapter.kt
  app/src/main/java/com/example/tripsync/ui/adapter/MyPlanDetailAdapter.kt
  app/src/main/java/com/example/tripsync/ui/dialog/UserAddDialogFragment.kt
  app/src/main/java/com/example/tripsync/ui/dialog/UserManageDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_user_manage_dialog.xml
  app/src/main/res/layout/myplan_detail_item.xml
Labels: enhancement

#51 [FEAT] planfragment
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tripsync/ui/fragment/plan/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupCalendarView.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/res/drawable/map_1.png
  app/src/main/res/drawable/map_2.png
  app/src/main/res/drawable/map_3.png
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_setup.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/setup_calendarview.xml
Labels: feature, design

#53 [FEAT] : MyPlan 조회 및 수정 기능 추가
  app/src/main/java/com/example/tripsync/data/PlanRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
Labels: enhancement

#55 [FEAT] : 캘린더
  app/build.gradle
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupCalendarView.kt
  app/src/main/res/drawable/calendar_selector_textcolor.xml
  app/src/main/res/drawable/transparent_calendar_element.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_setup.xml
  app/src/main/res/layout/setup_calendarview.xml
Labels: feature

#56 [FEAT] : 친구가 작성한 Plan 열람 및 수정 기능 추가
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/data/AuthRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/data/PlanRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/model/Plan.kt
  app/src/main/java/com/example/tripsync/model/User.kt
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/SignupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanUserNameAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
Labels: enhancement

#57 [FEAT] : 홈 아이템 클릭 이벤트
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFestivalAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeTravelAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchFragment.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/search_item.xml
  app/src/main/res/xml/fragment_search_xml_constraintlayout_scene.xml
Labels: feature, design

#59 Design/mypage
  app/src/main/java/com/example/tripsync/ui/adapter/BookmarkAreaAdapter.kt
  app/src/main/java/com/example/tripsync/ui/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/BookmarkManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/FriendManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/res/drawable/bookmark_item_delete.png
  app/src/main/res/drawable/ic_bookmark_delete.png
  app/src/main/res/drawable/tab_button_line.xml
  app/src/main/res/layout/bookmarkmanage_bookmark_item.xml
  app/src/main/res/layout/fragment_bookmark_manage.xml
  app/src/main/res/layout/fragment_friend_manage.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/friendmanage_friend_item.xml
Labels: feature, design

#60 [FIX] : ViewPager2 버그 수정
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/BookmarkManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPlanFragment.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPlanViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: enhancement

#62 [FEAT] : 내 여행지 리스트 아이템 접기/펼치기 기능 추가
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/ui/ExpandCollapseAnimation.kt
  app/src/main/java/com/example/tripsync/ui/adapter/MyPlanAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/BookmarkManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/FriendManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupListAdapter.kt
  app/src/main/java/com/example/tripsync/viewmodel/BookmarkManageViewModel.kt
  app/src/main/java/com/example/tripsync/viewmodel/FriendManageViewModel.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPlanViewModel.kt
  app/src/main/res/drawable/ic_plan_add.png
  app/src/main/res/drawable/ic_plan_go.png
  app/src/main/res/drawable/ic_plan_remove.png
  app/src/main/res/layout/fragment_my_plan.xml
  app/src/main/res/layout/myplan_detail_item.xml
  app/src/main/res/layout/myplan_plan_item.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#64 Feat/mypage
  app/src/main/java/com/example/tripsync/data/AuthRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/ui/adapter/FriendManageAdapter.kt
  app/src/main/java/com/example/tripsync/ui/dialog/UserManageDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/FriendManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/res/drawable/button_gray_dark.xml
  app/src/main/res/drawable/button_gray_light.xml
  app/src/main/res/layout/bookmarkmanage_bookmark_item.xml
  app/src/main/res/layout/fragment_bookmark_manage.xml
  app/src/main/res/layout/fragment_coin.xml
  app/src/main/res/layout/fragment_friend_add_dialog.xml
  app/src/main/res/layout/fragment_friend_manage.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_user_manage_dialog.xml
  app/src/main/res/layout/friendmanage_friend_add_item.xml
  app/src/main/res/layout/friendmanage_friend_item.xml
Labels: feature, design

#66 [FEAT] : 메모 기능 추가
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/DetailFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanMemoDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/res/drawable/ic_edit_text.png
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_plan_memo.xml
  app/src/main/res/layout/fragment_search.xml
Labels: feature

#67 [FEAT] : Plan & Set
  app/src/main/java/com/example/tripsync/model/Travel.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/NaverMapFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/TestModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/PlanSearchListDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/SearchViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/search/SearchAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupCalendarView.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/setupuseradd/SetupUserAddDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/setupuseradd/SetupUserAddDialogAdapter.kt
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/search_item.xml
Labels: feature, design

#70 Feat/mypage
  app/build.gradle
  app/src/main/java/com/example/tripsync/ui/dialog/FriendAddDialogFragment.kt
  app/src/main/java/com/example/tripsync/ui/dialog/UserManageDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/SignOutDialogFragment.kt
  app/src/main/java/com/example/tripsync/viewmodel/UserProfileViewModel.kt
  app/src/main/res/drawable/defalt_profile.jpg
  app/src/main/res/layout/fragment_friend_add_dialog.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_sign_out_dialog.xml
  app/src/main/res/layout/fragment_user_manage.xml
Labels: feature, design

#71 [FEAT] : 여행 리스트 실시간 갱신 기능 구현
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/data/PlanRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/java/com/example/tripsync/viewmodel/MyPlanViewModel.kt
Labels: enhancement

#72 [Desing] HomeUI
  app/src/main/java/com/example/tripsync/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeAreaAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/SwipeToDeleteCallback.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupCalendarView.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/res/drawable/btn_normal.xml
  app/src/main/res/drawable/selected_btn.xml
  app/src/main/res/drawable/setup_btn_round12.xml
  app/src/main/res/layout/area_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/setup_calendarview.xml
Labels: design

#74 [Design] : login UI
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/res/layout/bookmarkmanage_bookmark_item.xml
  app/src/main/res/layout/bookmarkmanage_category_item.xml
  app/src/main/res/layout/fragment_bookmark_manage.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/search_item.xml
  app/src/main/res/values/themes.xml
Labels: design

#76 [FEAT] : 프로필 이미지 URL 데이터베이스 저장 기능 구현
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/data/AuthRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/model/User.kt
  app/src/main/java/com/example/tripsync/ui/dialog/UserManageDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MainFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/viewmodel/UserProfileViewModel.kt
Labels: enhancement

#77 [DESIGN] : 탭 레이아웃
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/tripsync/ui/adapter/ViewPagerFragmentAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MainFragment.kt
  app/src/main/res/drawable/ic_tab_game.png
  app/src/main/res/drawable/ic_tab_game2.png
  app/src/main/res/drawable/ic_tab_home.png
  app/src/main/res/drawable/ic_tab_plan.png
  app/src/main/res/drawable/ic_tab_plan2.png
  app/src/main/res/drawable/ic_tab_profile.png
  app/src/main/res/drawable/ic_tab_profile2.png
  app/src/main/res/drawable/ic_tab_search.png
  app/src/main/res/drawable/ic_tab_search2.png
  app/src/main/res/drawable/test.xml
  app/src/main/res/layout/fragment_main.xml
Labels: design

#78 Feat/mypage
  app/src/main/java/com/example/tripsync/ui/dialog/UserManageDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/CoinFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/LoginFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/SignupFragment.kt
  app/src/main/res/drawable/button_signup_remove.png
  app/src/main/res/drawable/button_signup_remove.xml
  app/src/main/res/drawable/coin_text_no.png
  app/src/main/res/drawable/coin_text_start.png
  app/src/main/res/drawable/coin_text_yes.png
  app/src/main/res/drawable/defalt_profile.jpg
  app/src/main/res/drawable/defalt_profile.png
  app/src/main/res/drawable/defalt_profile_edit.png
  app/src/main/res/layout/fragment_coin.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/fragment_user_manage.xml
Labels: feature, design

#80 [FEAT] : BTN
  app/build.gradle
  app/src/main/java/com/example/tripsync/data/AuthRepositoryImpl.kt
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/adapter/BookmarkAreaAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/BookmarkManageFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeAreaAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/home/HomeFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/PlanUserNameAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/plan/plansearchlist/SearchViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupCalendarView.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SetupTitleDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/setupuseradd/SetupUserAddDialog.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/setupuseradd/SetupUserAddDialogAdapter.kt
  app/src/main/res/drawable/calendar_selector_textcolor.xml
  app/src/main/res/drawable/plan_user_profile.xml
  app/src/main/res/font/npsfont.ttf
  app/src/main/res/font/npsfont_extra.ttf
  app/src/main/res/layout/bookmarkmanage_bookmark_item.xml
  app/src/main/res/layout/fragment_setup.xml
  app/src/main/res/layout/plan_recycler_item.xml
  app/src/main/res/layout/plan_user_add_item.xml
  app/src/main/res/layout/plan_username_item.xml
  app/src/main/res/layout/search_item.xml
  app/src/main/res/layout/setup_calendarview.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, design

#82 [FIX] : 여행 세부계획 수정 시 앱이 다운되는 현상 해결
  app/src/main/java/com/example/tripsync/ui/activity/MainActivity.kt
  app/src/main/java/com/example/tripsync/ui/adapter/MyPlanAdapter.kt
  app/src/main/java/com/example/tripsync/ui/fragment/setup/SharedViewModel.kt
Labels: enhancement

#86 [DESIGN] : 커뮤니티 게시글 작성, 게시글 상세페이지 UI 레이아웃 제작
  app/src/main/java/com/example/tripsync/ui/fragment/CommunityContentFragment.kt
  app/src/main/java/com/example/tripsync/ui/fragment/CommunityWriteFragment.kt
  app/src/main/res/drawable/defalt_profile_edit.png
  app/src/main/res/drawable/ic_back.png
  app/src/main/res/drawable/ic_comment_send_button.png
  app/src/main/res/drawable/ic_menu.png
  app/src/main/res/layout/fragment_community_content.xml
  app/src/main/res/layout/fragment_community_write.xml
Labels: design
